#!/bin/bash

# help string to be printed when the user does not use it in the right way 
Help="
Wrong Usage....
Please use one one of the following parameters:
    1) mywc -c path/to/test/file.txt
            this option will print the number of bites in the wanted file.
    
    2) mywc -l path/to/test/file.txt
            this option will print the number of line in the wanted file.
    
    3) mywc -m path/to/test/file.txt
            this option will print the number of characters in the wanted file.
    
    4) mywc -w path/to/test/file.txt
            this option will print the number of words in the wanted file.
            
    1) mywc path/to/test/file.txt 
            this is the defeault parameter, the equivalent to the -c, -l and -w options. 
"

handle_default_param() {
    handle_bytes_param $1    
    handle_words_param $1
    handle_char_param $1
    handle_lines_param $1
}

handle_bytes_param() {
    local file=$1
    local bytes=0
    
    while IFS= read -r -n1 char
    do
        ((bytes++))
    done < "$file"
    
    echo "Bytes: $bytes in $file"
}

handle_words_param() {
    local file=$1
    local words=0
    local in_word=false
    
    while IFS= read -r -n1 char
    do
        if [[ $char =~ [[:space:]] ]]; then
            in_word=false
        elif [ "$in_word" = false ]; then
            ((words++))
            in_word=true
        fi
    done < "$file"
    
    echo "Words: $words in $file"
}

handle_lines_param() {
    local file=$1
    local lines=0
    
    while IFS= read -r line
    do
        ((lines++))
    done < "$file"
    
    echo "Lines: $lines in $file"
}

handle_char_param() {
    local file=$1
    local chars=0
    
    while IFS= read -r -n1 char
    do
        ((chars++))
    done < "$file"
    
    echo "Characters: $chars in $file"
}

# Check if no orgument have been provided, Or if the help command have been asked 
if  [ $# -eq 0 ] || [ "$1" = "help" ] || [ "$1" = "--help" ] || [ "$1" = "-h" ]; then 
    echo "$Help"
    exit 1 
fi

if [ "$1" = "-c" ]; then
    handle_bytes_param "$2"
    exit 0
elif [ "$1" = "-l" ]; then
    handle_lines_param "$2"
    exit 0
elif [ "$1" = "-m" ]; then
    handle_char_param "$2"
    exit 0
elif [ "$1" = "-w" ]; then
    handle_words_param "$2"
    exit 0
else
    # This is the default case
    if [ -f "$1" ]; then
        handle_default_param "$1"
    else
        echo "$Help"
        exit 1
    fi
fi
